### ISSUE TITLE
模块加载失败

### ISSUE THREAD

**Issue by naloder** [FuckCoolapk/FuckCoolapk#13]
环境:应用转生

Log:
https://docs.google.com/document/d/1S8xpaY3SYIfygzuNluFcDqsIaBjlOFT9KjMVe49x_9s

**Comment by lz233** [comment]
![image](https://user-images.githubusercontent.com/32504382/108466126-1e249a00-72be-11eb-9204-04a4f274705a.png)

**Comment by naloder** [comment]
@lz233 已修改权限

**Comment by lz233** [comment]
确实进不去。应用转生的问题。
考虑使用除太极外的其他框架。
