### ISSUE TITLE
为什么不支持太极？可以细🔒下原因吗

### ISSUE THREAD

**Issue by ameaninglessname** [FuckCoolapk/FuckCoolapk#14]
我看之前的issue里有说“本模块不支持太极”，想知道原因

是需要额外的维护量么？

**Comment by XGMO9** [comment]
@ameaninglessname 模块是开源的,你可以pr让它支持

**Comment by MlgmXyysd** [comment]
Best present for 423.

**Comment by MlgmXyysd** [comment]
> @ameaninglessname 模块是开源的,你可以pr让它支持

根据许可协议，该操作不被允许
